import { designSystemRules, componentDefinitionRules } from "./design-system.ts";

export const ESLINT_CONFIG = "eslint.design-system.config.mjs";
export const OXLINT_CONFIG = ".oxlintrc.design-system.json";

export function eslintConfig(
  files: string[],
  componentFiles: string[],
  ignoredProjects: string[] = [],
): string {
  return `// Generated by repo-gates init. Edit these scopes and rule overrides for your project.
// Rule docs: https://github.com/shadcn-ui/lint
import { plugin as shadcn } from "@shadcn/lint";
import tsParser from "@typescript-eslint/parser";
import { designSystemRules, componentDefinitionRules } from "@fantastic.dev/repo-gates/design-system";

export default [
  { ignores: ${JSON.stringify(["**/node_modules/**", "**/dist/**", "**/out/**", "**/.next/**", "**/coverage/**", "**/.git/**", "**/.worktrees/**", ...ignoredProjects])} },
  {
    files: ${JSON.stringify(files)},
    languageOptions: { parser: tsParser, parserOptions: { ecmaFeatures: { jsx: true } } },
    plugins: { shadcn },
    rules: {
      ...designSystemRules,
      // Override individual defaults here, e.g. "shadcn/no-inline-styles": "off".
    },
  },
  {
    files: ${JSON.stringify(componentFiles)},
    rules: { ...componentDefinitionRules },
  },
];
`;
}

export function oxlintConfig(
  files: string[],
  componentFiles: string[],
  ignoredProjects: string[] = [],
): string {
  // Oxlint JSON cannot import our preset, so materialize its rules within the UI scopes.
  return (
    JSON.stringify(
      {
        $schema: "./node_modules/oxlint/configuration_schema.json",
        categories: { correctness: "off" },
        jsPlugins: ["@shadcn/lint"],
        ignorePatterns: [
          "**/node_modules/**",
          "**/dist/**",
          "**/out/**",
          "**/.next/**",
          "**/coverage/**",
          "**/.git/**",
          "**/.worktrees/**",
          ...ignoredProjects,
        ],
        rules: {},
        overrides: [
          { files, rules: designSystemRules },
          { files: componentFiles, rules: componentDefinitionRules },
        ],
      },
      null,
      2,
    ) + "\n"
  );
}
